theme: jekyll-theme-leap-day
title: [The title of your site]
description: [A short description of your site's purpose]
show_downloads: true
github:
  zip_url: https://binbot.app/download
  another_url: https://binbot.app/download
YT Wideo: https://binbot.app/download
